name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 022499025438.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image
        run: |
          # Construye solo la imagen con la etiqueta 'latest'
          docker build -t 022499025438.dkr.ecr.us-east-1.amazonaws.com/ecr_hola_mundo:latest .

      - name: Push Docker Image to Amazon ECR
        run: |
          # Empuja solo la imagen con la etiqueta 'latest', sin crear otra imagen
          docker push 022499025438.dkr.ecr.us-east-1.amazonaws.com/ecr_hola_mundo:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
